update dependency. Remove babel
bespoyasov/ttt-tdd pull request #13
Opened 2022-01-24 18:53 UTC by AlexanderAverin

Обновил зависимости. Убрал babel, mocha и chai. Изменил фрагменты книги, где были 'куски' тестов. В секции game перенёс файл GameBuilder.js из test в src, и изменил файл конфигурации webpack.

2022-01-25 08:12 UTC, bespoyasov reviewed
Офигенно, спасибо! 👀 
У меня пара вопросов возникла, пока читал диффы. Обсудим? 😃

2022-01-25 08:12 UTC, bespoyasov commented on book/src/sections/32.html
> +    expect(domController.game.acceptUserMove.called).toBeTruthly()
Лучше [`toBeTrue()` или `toBe(true)`](https://stackoverflow.com/questions/32615713/tobetrue-vs-tobetruthy-vs-tobetrue), так как мы проверяем не «любое неложное значение», а «точно истину».

2022-01-25 08:12 UTC, bespoyasov commented on book/src/sections/37.html
> +import Game from './Game.js'
А мы добавляем расширение из-за экспериментальной поддержки модулей в Jest?

2022-01-25 08:12 UTC, bespoyasov commented on game/src/Game.js
> +import _ from 'lodash'
Я думаю, мы можем убрать Lodash, сделать клонирование через быстрый хак с `JSON.parse(JSON.stringify(...))`, а когда появится широкая поддержка [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone), заменить хак не него.

2022-01-25 08:12 UTC, bespoyasov commented on game/src/Game.js
> +import _ from 'lodash'
(Ну или по крайней мере не тащить весь Lodash, а [тришейкуть](https://lodash.com/per-method-packages) его, чтобы включить только `cloneDeep` в итоговый бандл.)

2022-01-25 08:18 UTC, AlexanderAverin commented on book/src/sections/32.html
> +    expect(domController.game.acceptUserMove.called).toBeTruthly()
Да, согласен. Иначе, в перспективе может возникнуть такие ситуации, при которых этот тест будет пройден. Поправлю.

2022-01-25 08:21 UTC, AlexanderAverin commented on book/src/sections/37.html
> +import Game from './Game.js'
Это я случайно поправил. Я обычно пишу расширение

2022-01-25 08:29 UTC, AlexanderAverin commented on book/src/sections/37.html
> +import Game from './Game.js'
> Это я случайно поправил. Я обычно пишу расширение, по привычке.

2022-01-25 08:48 UTC, AlexanderAverin commented on game/src/Game.js
> +import _ from 'lodash'
Да, попробую сделать через `JSON.stringify ()`, а если не получится, вот так `import { cloneDeep } from 'lodash'`.

2022-01-26 09:47 UTC, AlexanderAverin commented on game/src/Game.js
> +import _ from 'lodash'
Вроде, закончил 😀

2022-01-26 13:24 UTC, bespoyasov reviewed
Отлично!

Я ещё думаю вынести снипет с `JSON.parse(JSON.stringify(...))` в отдельную функцию-утилиту, чтобы не повторяться, и будет ок 🙃

2022-01-26 13:26 UTC, AlexanderAverin commented
Ага, уже сделал, просто не ещё не сделал комит.

2022-01-26 13:32 UTC, AlexanderAverin commented
А куда лучше разместить функцию копирования, в const.js ?

2022-01-26 13:34 UTC, AlexanderAverin commented
> А куда лучше разместить функцию копирования, в const.js ?

Сейчас она в Game.js

2022-01-26 14:09 UTC, bespoyasov commented
> А куда лучше разместить функцию копирования, в const.js ?

Вообще, по-хорошему, её бы сделать абстрактной и вынести в отдельный модуль. Но я предлагаю сильно не заморачиваться и сделать приватный метод в классе `Game` 😃 

```js
export default class Game {
  // ...
  
  checkGame() {
    if (this.isWinner(this._userName)) return `${this._userName} won!`
    if (this.isWinner(this._computerName)) return `${this._computerName} won!`
    if (this._getFreeCellsCount() === 0) return `nobody won :–(`
    return 'continue'
  }


  _copyBoard(state) {
    return JSON.parse(JSON.stringify(state));
  }

  _updateBoard(x, y, config={}) {
    const {symbol=this._userMoveSymbol} = config
    this._board[x][y] = symbol
  }

  // ...
}
```

И использовать его потом в конструкторе и методе `clear`.

2022-01-26 14:19 UTC, AlexanderAverin commented
Думаю, можно вынести в отдельный модуль, иначе может показаться, что метод `deepClone()` нужен только в объекте `Game`

2022-01-26 14:23 UTC, AlexanderAverin commented
> Думаю, можно вынести в отдельный модуль, иначе может показаться, что метод `deepClone()` нужен только в объекте `Game`

Хотя, в нашем случае можно и как приватный метод, ведь нам не нужна эта функция в других модулях (:

2022-01-27 10:35 UTC, bespoyasov commented on game/src/Game.js
> +  _deepClone(coll) {
Предлагаю ещё назвать метод `_cloneBoardState`. 

Мы уже сделали сделали его конкретным для этого уровня абстракции, поэтому лучше передать в названии намерение, с которым этот метод создавали.

Так как он должен скопировать состояние «доски», которое ему передают аргументом, лучше прямо так в названии и написать. Так мы сделаем метод декларативнее, при чтении будет понятно, зачем он нужен 🙂

2022-01-28 12:31 UTC, bespoyasov approved these changes
Огонь, спасибо! 👀 

Я на выходных ещё раз всё внимательно посмотрю, и если всё ок, то вмёржу и обновлю проект. Спасибо за помощь! 🥳

2022-01-28 13:01 UTC, AlexanderAverin commented
😃

2022-01-28 14:59 UTC, bespoyasov requested changes

2022-01-28 14:59 UTC, bespoyasov commented on book/package.json
> +    "gulp": "^4.0.2",
Заметил, что после поднятия версии Gulp проект перестал собираться:

```
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/ttt-tdd/book/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/ttt-tdd/book/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/ttt-tdd/book/gulpfile.js:34:6)
```

Обратная совместимость — частая проблема при обновлении мажорной версии пакетов. Здесь нам надо будет немного [обновить код `gulp`-файла](https://stackoverflow.com/questions/51098749/everytime-i-run-gulp-anything-i-get-a-assertion-error-task-function-must-be).

Если есть желание, то можно продолжить работу над этим прямо в текущем PR. А хочется остановиться, то можно откатить Gulp то предыдущей версии, к состоянию, когда проект собирается 🙂

2022-01-28 16:05 UTC, AlexanderAverin commented on book/package.json
> +    "gulp": "^4.0.2",
Вроде, сборка заработала. Пока пришлось убрать кусочек кода, связанный с сервис воркером (вот этот:
`  gulp.src('./src/sw.js')
    .pipe(gulp.dest('./dist/'))`
).

2022-01-28 17:46 UTC, bespoyasov commented on book/package.json
> +    "gulp": "^4.0.2",
Да, верно. Я там завёл [отдельное ишью](https://github.com/bespoyasov/ttt-tdd/issues/12) для этого. Прошлая попытка сделать офлайн была не очень успешной :–)

2022-01-28 18:00 UTC, bespoyasov approved these changes

2022-01-28 18:00 UTC, merged